### PR TITLE
cleanup

### PR DESCRIPTION
**Pull request by burtbeckwith**

### CODE REVIEW

**Comment by MayGo** [comment]
Thank you for pull request! Very nice work.
I analyised generated code with Codenarc, but plugin itself was forgotten.
What kind of automatic code analysers did you use?

**Comment by MayGo** [comment]
I only put back hibernate dependency, its needed in DomainHelper.groovy
compile(":hibernate4:4.3.6.1") {
    export = false
}

**Comment by burtbeckwith** [comment]
I've used Codenarc in the past and I like it a lot, but I usually rely on tests to ensure code quality.

**Comment by MayGo** [comment]
I have problem publishing this plugin
Publishing to http://grails.org/api/v1.0/publish/scaffold-angular/1.2
Error Failed to publish plugin: Permission denied

Is this because i submitted app name ScaffoldAngular instead scaffold-angular?
(same problem with scaffold-core plugin)

**Comment by burtbeckwith** [comment]
I edited the permissions so you should be able to publish now.

**Pull request merged**
